### ISSUE TITLE
Incorrect highlighting when colon is used inside yaml literal style

### ISSUE THREAD

**Issue by aeschli** [textmate/yaml.tmbundle#17]
_From @tnikodym on October 12, 2016 14:34_

- VSCode Version: 1.6.0
- OS Version: OS X El Capitan (10.11.6)

See the screenshot below. When a colon is used inside [literal content](http://www.yaml.org/spec/1.2/spec.html#id2795688) (indicated by | character), the entire line up to the colon is highlighted as a property. 

![screen shot 2016-10-12 at 16 27 17](https://cloud.githubusercontent.com/assets/19610642/19314007/cfe269a0-9098-11e6-94b5-46cb3438850f.png)

Note: I have not seen this issue in the previous version of VSCode. 

_Copied from original issue: Microsoft/vscode#13601_

**Comment by infininight** [comment]
This issue and the other four just closed as duplicates all are tied to the same underlying issue. The string rule is not being properly entered in `#block-scalar` due to how `\G` is being interpreted during a line re-parse. For many contexts it can appear to be working and it will work when a file is initially read but not as being entered or upon editing the first line.

This is a complicated issue to fix, working on how to do so now.

**Comment by ValentinFunk** [comment]
Is there anything we can do to help? Would more test cases help?

**Comment by infininight** [comment]
There is not, this is a current limitation of the grammar engine and I don't believe it is possible to fix on the grammar side. Unless I figure out an alternate method this will need to wait for a fix on the parser side of things.

**Comment by ValentinFunk** [comment]
@aeschli seeing the answer above, would it make sense then to reopen the vscode issue https://github.com/Microsoft/vscode/issues/13601 since it can't be fixed in the grammar and actually needs a change on the vscode side as well?

**Comment by infininight** [comment]
@Kamshak So a better description of the issue since I haven't talked it about it yet in these issues:

`\G` was added as a zero width assertion to match the end of the parent begin that started the active pattern array. This is a non-standard extension to the regex parser by co-opting an already existing but unused assertion. TextMate grammars are line-based which means that each line is parsed separately, and changes on a line only necessitate repaying that single line unless it causes a new state to be caused which will cause latter lines to be re-parsed as well.

The current limitation is that the state that `\G` uses is not saved from a previous line when a line is re-parsed due to editing. This is why there is inconsistency noticed, the initial parsing runs the line through in order and the state is saved. Due to the line based nature of the parser this isn't really so much a bug as just a limitation of the parser, a exception would have to be made in this case to save the state for later re-use.

If we decide to make this change it will need to be updated in VSCode and GitHub as well, I'll open issues with both if this is the course taken. The alternative is to find another solution to workaround the limitation, but so far I have not been successful in finding an alternative, without being able to save the state it's hard to not prematurely exit the rule.

**Comment by trondhindenes** [comment]
Any movement on this? It's a very annoying bug :-(

**Comment by ValentinFunk** [comment]
Since @infininight has kindly explained the issue in a very detailed way, maybe someone familiar with VSCode would be willing to take a look at it :) It seems we're stuck without some help

Sorry for tagging you out of the blue @alexandrudima @bpasero, is there a chance you could take a quick look at this issue (or tag someone who could)? Would be very much appreciated! :heart:

**Comment by thislooksfun** [comment]
You mentioned that it was a parsing issue. I just wanted to chime in and say that multiline string highlighting works perfectly if the string is enclosed in quotes.

<img width="548" alt="Screen Shot 2019-12-04 at 8 59 24 PM" src="https://user-images.githubusercontent.com/5367333/70200047-f6f1a500-16d8-11ea-895e-961a1c794830.png">

```yaml
test:
  "note that this green as it should be:
  when there's no colon, it also works correctly
  same solution here: and after the colon it's OK"

test: |
  but when using a pipe, it breaks again:
  when there's no colon, it works correctly
  same problem here: but after the colon it's OK
    
test: >
  when using a right arrow it also breaks:
  when there's no colon, it works correctly
  same problem here: but after the colon it's OK

test:
  "this also works correctly"

test: |
  as does this
  
test: >
  and this

test:
  and also this
```

Hopefully this helps narrow down the issue and/or potential solutions.
