### ISSUE TITLE
YAML Syntax highlighting error on multiline strings

### ISSUE THREAD

**Issue by aeschli** [textmate/yaml.tmbundle#23]
_From @Yajo on May 3, 2018 11:2_

When you use `>` or `|` [to indicate that the following indented code is a multiline string in YAML](http://yaml.org/spec/1.2/spec.html#id2760844), special characters are highlighted as if it were normal YAML:

![captura de pantalla de 2018-05-03 11-57-21](https://user-images.githubusercontent.com/973709/39573049-7b20d26c-4ec9-11e8-8ddd-88927bbf8d67.png)
![captura de pantalla de 2018-05-03 11-59-22](https://user-images.githubusercontent.com/973709/39573050-7b431d86-4ec9-11e8-8653-02bed5f3ad22.png)

_Copied from original issue: Microsoft/vscode#49112_

**Comment by infininight** [comment]
Sample in question:

```yaml
- &create_user
  name: >
    create resent bucket iam user
    {{ user.key }}
    - one
    - [ two ]
    &anchor yes
    1
  when:
    - *aws_filter
    - *present_filter
  iam:
    name: "{{ user.key }}"
    iam_type: user
    state: present
    access_key_state: create
    key_count: "{{user_key_count}}"
  register: result
```
