### ISSUE TITLE
Wrong YAML syntax highlighting in some corner cases for strings

### ISSUE THREAD

**Issue by aeschli** [textmate/yaml.tmbundle#29]
_From @Yajo on July 30, 2018 9:21_

Issue Type: <b>Bug</b>

Comments inside the image explain the wrong syntax highlighting problems; see:
![captura de pantalla de 2018-07-30 10-20-20](https://user-images.githubusercontent.com/973709/43388884-402dbbc6-93e2-11e8-8b2e-6708f062c195.png)

_Copied from original issue: Microsoft/vscode#55355_

**Comment by aeschli** [comment]
@Yajo Would you mind pasting the code example here? Thanks a lot!

**Comment by aeschli** [comment]
_From @texastoland on July 31, 2018 4:57_

Same here:

```yaml
key: string
  "flows" | here
#         ^^^^^^ highlighted
```

Surely related to textmate/yaml.tmbundle#17.

**Comment by aeschli** [comment]
_From @Yajo on July 31, 2018 9:50_

```yaml
# Highlight here is OK
- name: build docker-compose project {{ project.key }}
  # Highlight is misleading. All of this block is a string
  split spaces: |
    - i'm a string
    - [not an array]
    - {nor a dict}
  # same here
  join spaces: >
    - i'm a string
    - [not an array]
    - {nor a dict}
  when:
    # This is all a single string
    - not build_cache|bool or "ERROR: for odoo" in result.stderr
  command:
    # Highlighting in line 42 is misleading. All of this is a string too
    docker-compose build --pull
    {% if not build_cache|bool %} --no-cache {% endif %}
```
