### ISSUE TITLE
Grammar does not recognize comments with a tab in them

### ISSUE THREAD

**Issue by alexr00** [textmate/yaml.tmbundle#36]
```yaml
redis:
  # good comment
  enabled: true
  # 	bad comment
  image:
    pullPolicy: IfNotPresent
```

![image](https://user-images.githubusercontent.com/15629116/108858143-d6518b80-75b9-11eb-9bd2-f98e628791cf.png)

Originally from @rcjsuen in https://github.com/microsoft/vscode/issues/117407
